### PR TITLE
ptbr translation

### PR DESCRIPTION
**Pull request by mezysinc**

### CODE REVIEW

**Comment by cvzi** [comment]
Thank you! 👍

**Comment by mezysinc** [comment]
Hello cvzi,

It looks like info on gplay is still in 'En'. Do you have somewhere other set of strings for that? Or it wasn't updated yet? If it's on github let me know where. Thanks

**Comment by cvzi** [comment]
The description in the play store?
No I have not translated or put it on github yet, but I can add it to git later today.

**Comment by mezysinc** [comment]
Ok, when you get a chance upload that to github and let me know about it. I guess it make sence to translate it too. Gets more views & afterwards users.

**Comment by cvzi** [comment]
The files are now here: https://github.com/cvzi/ScreenshotTile/tree/master/fastlane/metadata/android
The relevant files are [full_description.txt](https://github.com/cvzi/ScreenshotTile/blob/master/fastlane/metadata/android/en-US/full_description.txt) and [short_description.txt](https://github.com/cvzi/ScreenshotTile/blob/master/fastlane/metadata/android/en-US/short_description.txt)
The code for the folder should be `pt-BR`

**Comment by cvzi** [comment]
You don't need to translate it "exact", just write it how you like and what you think is best

**Pull request merged**
