### PR TITLE
Some fixes about Material3 (Material You)

### PR DESCRIPTION
**Pull request by user0-tb**
Not the full app has Material3. This PR will fix this. 
Screenshot_20231216_100110_com github cvzi screenshottile debug
Screenshot_20231216_100105_com github cvzi screenshottile debug
Screenshot_20231216_100054_com github cvzi screenshottile debug
Screenshot_20231216_100039_com github cvzi screenshottile debug

### CODE REVIEW

**Comment by user0-tb** [comment]
Completed 
Screenshot_20231216_102249_com github cvzi screenshottile debug
Screenshot_20231216_102245_com github cvzi screenshottile debug
Screenshot_20231216_102238_com github cvzi screenshottile debug
Screenshot_20231216_102224_com github cvzi screenshottile debug

**Comment by user0-tb** [comment]
Test apk:
[app_debug (16).zip](https://github.com/cvzi/ScreenshotTile/files/13692037/app_debug.16.zip)

**Comment by user0-tb** [comment]
The text size need to be bigger.

**Comment by user0-tb** [comment]
Now bigger text. I'm not going to upload screenshots. The test APK is updated. @cvzi

**Comment by cvzi** [comment]
I will take a look later. 

Can I include your name in the main activity as a contributor? For example below the list of translators.

**Comment by user0-tb** [comment]
Sure, do it. Use my username (user0-tb)

**Comment by user0-tb** [comment]
[](url)

**Review by cvzi — APPROVED** [review]

**Comment by user0-tb** [comment]
Thanks for merging! When will the changes be released to the Playstore?Am 16.12.2023 23:40 schrieb cvzi ***@***.***>:
@cvzi approved this pull request.

**Comment by cvzi** [comment]
I can `git tag` a new version later today. Then we need to wait until F-Droid picks up the new version, builds the apk and signs it, this can take a few days. When F-Droid has the new version, then I will upload it to Playstore

**Comment by user0-tb** [comment]
Thanks! Looks like it's about to be released 🎉! Only the signing must be completed by a human, so it will take a little bit.

**Comment by user0-tb** [comment]
It's now on F-Droid🎉! You can now publish!

**Comment by cvzi** [comment]
Yes, I already uploaded the apk file to Google Play a few hours ago. Now Google is reviewing the apk. That review usually takes less than a day and then it's automatically published. 
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by user0-tb** [comment]
Thanks!

**Pull request merged**
