### PR TITLE
updated ptbr translation

### PR DESCRIPTION
**Pull request by mezysinc**
updated ptbr strings + translated missing ones

### CODE REVIEW

**Comment by cvzi** [comment]
Thanks so much!
I will update the app in a few days

**Comment by mezysinc** [comment]
I post it in here because is just an idea for new option in configurations,

When pressing tile/button from 'quick pulldown bar' it makes screenshots right away or in 'delay' that was set beforehand.

I'd be great to add option in configs (optional for whoever would prefer to activate this), that changes default behavior & goes right away to 'select area' after pressing 'tile/button' in quick menu.

Now in order to 'select area' you have to
1) long press 
2) press 'select area' option
3) select area (with finger)
4) confirm
5) screenshot is taken

Adding new option in configurations with action that -- goes straight away to 'selecting area' -- (and maybe even making screenshot right away  after finger was lifted off (without confirmation)

New behavior would be:
1) press tile 
2) select area (with finger)
3) finger was lifted off, screenshot was taken

Toggle:
Select area right away

Short description
Go straight away to area selection & take screenshot

Just a thought

**Comment by cvzi** [comment]
Yes good idea
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by cvzi** [comment]
On second thought, it might be better to add a new button/tile that goes directly to the "select area".

**Comment by mezysinc** [comment]
But then you would have ppl complaining that it was better before, comments like "I can't make screenshots anymore". When you add optional (toggle entry) someone would have to:

1) read configurations menu
2) read all available options
3) activate it (if understands what it does)

second tile could get most ppl lost, (it gets more complicated) at least for those who don't like reading much

But for me both ways could work, now let's try to guess what would work for others, hard to tell

**Pull request merged**
