### PR TITLE
Make the App Material3 (Material You)

### PR DESCRIPTION
**Pull request by user0-tb**
Make the App moderner with the newest material design.

### CODE REVIEW

**Comment by user0-tb** [comment]
Screenshot_20231215_134933

**Comment by user0-tb** [comment]
@cvzi It's now reads for review.

**Comment by cvzi** [comment]
Wow 🤯
I'll take a look later

**Comment by user0-tb** [comment]
Thanks!!!

**Comment by user0-tb** [comment]
[app_debugzip](https://github.com/cvzi/ScreenshotTile/files/13687553/app_debug.15.zip)
If you need, here is an Test apk file

**Comment by user0-tb** [comment]
@cvzi any new?

**Review by cvzi — APPROVED** [review]

**Comment by cvzi** [comment]
Looks good. Thanks for the PR!

**Comment by cvzi** [comment]
I will probably wait until after weekend to release new version though.
I recently added a few new strings and I want to wait, if some people will contribute translations on crowdin.com on the weekend.

**Comment by user0-tb** [comment]
Thanks!

**Pull request merged**
